mainfont: "Gentium Book Plus"
mainfontfallback:
  - "TeXGyreDejaVuMath-Regular:mode=harf"
  - "Noto Color Emoji:mode=harf"
<<<<<<< HEAD
  - "Droid Sans Fallback:mode=harf"
=======
<<<<<<< HEAD
  - "Droid Sans Fallback:mode=harf"
=======
  - "Droid Sans Fallback:mode=harf"
header-includes: |
  \usepackage{graphicx}
  \usepackage{fancyhdr}
  \fancypagestyle{firstpage}{
    \fancyhf{}
    \renewcommand{\headrulewidth}{0pt}
  }
  \fancypagestyle{otherpage}{
    \fancyhf{}
    \renewcommand{\headrulewidth}{0pt}
  }
  \pagestyle{otherpage}
  \thispagestyle{firstpage} 
>>>>>>> 9663723 (test to fix latex compilation error)
>>>>>>> 87bab3a (test to fix latex compilation error)
